<a href="https://colab.research.google.com/github/himanshu3103/PyTorch/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals

In [131]:
print("I am here to learn Pytorch")

I am here to learn Pytorch


In [132]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [133]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## Introduction to Tensors

### Creating Tensors

In [134]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [135]:
scalar.ndim

0

In [136]:
#Get tensor back as python int
scalar.item()

7

In [137]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [138]:
vector.ndim

1

In [139]:
vector.shape

torch.Size([2])

In [140]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [141]:
MATRIX.shape

torch.Size([2, 2])

In [142]:
MATRIX.ndim

2

In [143]:
#TENSOR
TENSOR = torch.tensor([[[1,3,4],
                        [5,6,7],
                        [7,3,5]]])
TENSOR

tensor([[[1, 3, 4],
         [5, 6, 7],
         [7, 3, 5]]])

In [144]:
TENSOR.shape

torch.Size([1, 3, 3])

In [145]:
print(f"Dimension 0 is : {TENSOR[0]}")
print(f"Dimension 1 is : {TENSOR[0][0]}")
print(f"Dimension 2 is : {TENSOR[0][0][0]}")

Dimension 0 is : tensor([[1, 3, 4],
        [5, 6, 7],
        [7, 3, 5]])
Dimension 1 is : tensor([1, 3, 4])
Dimension 2 is : 1


In [146]:
TENSOR1 = torch.tensor([[[1,3,4],
                        [5,6,7],
                        [7,3,5]],
                        [[11,12,13],
                         [12,45,32],
                         [23,42,56]]])
TENSOR1

tensor([[[ 1,  3,  4],
         [ 5,  6,  7],
         [ 7,  3,  5]],

        [[11, 12, 13],
         [12, 45, 32],
         [23, 42, 56]]])

In [147]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensors

In [148]:
#Create a random tensor of size [3,4]
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1169, 0.0511, 0.8245, 0.3651],
        [0.8011, 0.6368, 0.5310, 0.1116],
        [0.9202, 0.0243, 0.8319, 0.0815]])

In [149]:
random_tensor.ndim

2

In [150]:
random_tensor.shape

torch.Size([3, 4])

In [151]:
random_tensor.size()

torch.Size([3, 4])

In [152]:

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels ={R,G,B}
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [153]:
torch.rand(size=(3,3))

tensor([[0.4750, 0.2277, 0.7627],
        [0.6821, 0.9541, 0.6022],
        [0.3057, 0.7321, 0.9885]])

### Zeroes and Ones

In [154]:
#Create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [155]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [156]:
#Create a tensor with all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [157]:
ones.dtype

torch.float32

### Creating range of tensor and tensors-like

In [158]:
#torch.range() has been deprecated
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [159]:
step = torch.arange(start=0,end=1300,step=120)
step

tensor([   0,  120,  240,  360,  480,  600,  720,  840,  960, 1080, 1200])

In [160]:
#Creating a tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [161]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note:** 3 biggest errors with Tensors in Pytorch
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device 

In [162]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,4.0,5.0],
                               dtype=None, #by default dtype=torch.float32
                               device=None, #by default device="cpu"
                               requires_grad=False #whether or not to track gradients with this tensor
                               )
float_32_tensor

tensor([3., 4., 5.])

In [163]:
float_32_tensor.dtype

torch.float32

In [164]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

### Getting information from Tensor (tensor attributes)
1. Tensors not right datatype - for datatype use tensor.dtype
2. Tensors not right shape - for shape use tensor.shape
3. Tensors not on right device - for device use tensor.device

### Manipulating Tensors (tensor operations)
Tensor Operations:
* Addition
* Subtraction
* Multiplication(element wise)
* Division
* Matrix Multiplication 

In [165]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor = tensor+10

In [166]:
#Multiplication
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [167]:
#try out torch in-built operations
torch.mul(tensor,10)

tensor([1100, 1200, 1300])

### Matrix Multiplication
Two main ways to perform multiplication in neural networks
1. Element wise
2. Matrix Multiplication (Dot Product)

There are two main rules to matrix multiplication : 
1. The **inner dimension** must match:
  * `(3,2) @ (2,3)` will work
2. Resulting matrix will have the shape of **outer dimensions**:
  * `(2,3) @ (3,2)` will give `(2,2)`

In [168]:
#Element wise
tensor_mul = torch.tensor([3,4,5])
print(tensor_mul, "*", tensor_mul)
print(f"Equals to : {tensor_mul*tensor_mul}")

tensor([3, 4, 5]) * tensor([3, 4, 5])
Equals to : tensor([ 9, 16, 25])


In [169]:
torch.matmul(tensor_mul,tensor_mul)

tensor(50)

In [170]:
#Dealing with errors
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
#for multiplying we need to take the transpose of the second matrix
tensor_B.T #Transpose operation
print(f"Transposed matrix is: {tensor_B.T}")

Transposed matrix is: tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


In [171]:
%%time 
torch.mm(tensor_A,tensor_B.T) #short for torch.matmul()

CPU times: user 153 µs, sys: 14 µs, total: 167 µs
Wall time: 175 µs


tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, sum, etc (Tensor Aggregation)

In [172]:
#Create a tensor
x = torch.arange(1,101,1)
x.dtype #it creates a tensor of datatype int64

torch.int64

In [173]:
#Find the min 
torch.min(x), x.min()

(tensor(1), tensor(1))

In [174]:
#Find the max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [175]:
#Mean
#this wont works because of the dtype being long
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() #converting to float32

(tensor(50.5000), tensor(50.5000))

In [176]:
#Sum 
torch.sum(x), x.sum()

(tensor(5050), tensor(5050))

### Finding positional min and max

In [177]:
#Arg max --> returns the index of the largest element 
x.argmax()

tensor(99)

In [178]:
#Arg min --> returns the index of the smallest element
x.argmin()

tensor(0)

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors
* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* **Stacking** - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* **Squeeze** - removes all `1` dimensiona from a tensor
* **Unsqueeze** - add a `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [179]:
#Creating a tensor
import torch
x = torch.arange(1.,11.)
x, x.shape, x.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 torch.float32)

In [180]:
# Add an extra dimension
# Reshape has to be compatible with the original size
x_reshaped = x.reshape(1,10)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [181]:
#Make a column vector
x_reshaped = x.reshape(10,1)
x_reshaped

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [182]:
x_reshaped = x.reshape(5,2)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [183]:
#Change the view 
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [184]:
#Changing z changes x as the view of the tensor shares the same memory as the original input
# z = z.reshape(2,5)
# print(f"The z tensor is : {z}")
# print("\n")
# print(f"The x tensor is: {x}")
z[:,0] = 23
print(f"The z tensor is : {z}")
print(f"The x tensor is: {x}")

The z tensor is : tensor([[23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
The x tensor is: tensor([23.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [185]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[23., 23., 23., 23.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [186]:
x_stacked.shape

torch.Size([10, 4])

In [187]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
x_stack_dim_0 = torch.stack([a,b],dim=0)
x_stack_dim_1 = torch.stack([a,b],dim=1)
h_stack = torch.hstack((a,b))
v_stack = torch.vstack((a,b))
print(f"Stacking using Stack dim = 0 {x_stack_dim_0}")
print(f"Stacking using Stack dim = 1 {x_stack_dim_1}")
print(f"Stacking using hstack {h_stack}")
print(f"Stacking using vstack {v_stack}") #Stacking along dim = 0 is same as vstack

Stacking using Stack dim = 0 tensor([[1, 2, 3],
        [4, 5, 6]])
Stacking using Stack dim = 1 tensor([[1, 4],
        [2, 5],
        [3, 6]])
Stacking using hstack tensor([1, 2, 3, 4, 5, 6])
Stacking using vstack tensor([[1, 2, 3],
        [4, 5, 6]])


In [188]:
#Squeeze Method
#torch.squeeze() - removes all single dimensions from a target tensor
x_tensor = torch.rand(2,3,1)
print(f"Previous tensor: {x_tensor}")
print(f"Previous tensor shape: {x_tensor.shape}")

## Removing the extra single dimensions from the tensor
x_squeezed = x_tensor.squeeze()
print(f"New tensor is: {x_squeezed}")
print(f"New tensor shape is: {x_squeezed.shape}")

Previous tensor: tensor([[[0.9272],
         [0.1549],
         [0.4140]],

        [[0.7797],
         [0.2097],
         [0.5794]]])
Previous tensor shape: torch.Size([2, 3, 1])
New tensor is: tensor([[0.9272, 0.1549, 0.4140],
        [0.7797, 0.2097, 0.5794]])
New tensor shape is: torch.Size([2, 3])


In [189]:
#Unsqueeze Method
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"The prev tensor: {x_squeezed}")
print(f"Shape of prev: {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New tensor shape: {x_unsqueezed.shape}")


The prev tensor: tensor([[0.9272, 0.1549, 0.4140],
        [0.7797, 0.2097, 0.5794]])
Shape of prev: torch.Size([2, 3])

New tensor: tensor([[[0.9272, 0.1549, 0.4140],
         [0.7797, 0.2097, 0.5794]]])
New tensor shape: torch.Size([1, 2, 3])


In [202]:
#Permute
#torch.permute() - rearranges the dimensions of a target tensor in a specified order
#Returns a view of the original tensor input with its dimensions permuted.
x_original = torch.rand(size=(224,224,3)) #[height,width,colour_channels]
x_permuted = x_original.permute(2,0,1) # 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [205]:
x_original[0,0,0] = 0.700
x_permuted[0,0,0] #since they are the view of each other therefore changes in one reflects on the other one i.e they share the same memory

tensor(0.7000)

### Indexing(selecting data from tensor)

In [206]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [207]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [208]:
x[0,0] #same as x[0][0]

tensor([1, 2, 3])

In [209]:
x[0,0,0] #same as x[0][0][0]

tensor(1)

In [217]:
#Prints the complete tensor
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [222]:
#All the values of the zeroth dimension and 0th index of the first dimension
x[:,0]

tensor([[1, 2, 3]])

In [226]:
#All the values of the zeroth and first dimension but only the 0th index of second dimension
x[:,:,0]

tensor([[1, 4, 7]])

In [223]:
#All the values of the 0 dimension but only the 1 index of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [224]:
#Get index 0 of the 0th and 1st dimension and all the values of the second dimension
x[0,0,:]

tensor([1, 2, 3])

### Pytorch Tensors and Numpy Array
* Data in NumPy and we want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [227]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy->pytorch, pytorch reflects numpy's default datatype float64. To convert to pytorch's default tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [228]:
'''The returned tensor and ndarray share the same memory. 
Modifications to the tensor will be reflected in the ndarray and vice versa. 
The returned tensor is not resizable. '''
array += 1
tensor

tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [233]:
# Tensor to Numpy array 
tensor_py = torch.ones(7)
numpy_np = tensor_py.numpy()
tensor_py, numpy_np

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [234]:
#Changing the tensor changes the numpy array and vice versa
tensor_py[1] = 2
numpy_np

array([1., 2., 1., 1., 1., 1., 1.], dtype=float32)

### Reproducibilty in Pytorch
To reduce the randomness in neural networks, Pytorch comes with the concept of **random seed**.
<br>https://pytorch.org/docs/stable/notes/randomness.html
<br>https://link.springer.com/article/10.3758/bf03207952

In [235]:
import torch
#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(f"Random tensor A: {random_tensor_A}")
print(f"Random tensor B: {random_tensor_B}")
print(random_tensor_A==random_tensor_B)

Random tensor A: tensor([[0.8559, 0.7418, 0.1910, 0.5269],
        [0.6378, 0.0400, 0.8227, 0.1225],
        [0.8277, 0.7441, 0.5372, 0.8586]])
Random tensor B: tensor([[0.0610, 0.5404, 0.3909, 0.8656],
        [0.1572, 0.4777, 0.4736, 0.1055],
        [0.0959, 0.3135, 0.1662, 0.7391]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [237]:
# Let's make some random but reproducible tensors
import torch

#Set the random seed 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Random tensor C: {random_tensor_C}")
print(f"Random tensor D: {random_tensor_D}")
print(random_tensor_C==random_tensor_D)

Random tensor C: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Random tensor D: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running Tensors and PyTorch objects on GPUs

In [1]:
!nvidia-smi

Fri May 12 20:26:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
#Check if CUDA is available
import torch
torch.cuda.is_available()

True

It's best practice to write device agnostic code in Pytorch 
<br> https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [3]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#Count the number of devices
torch.cuda.device_count()

1

In [5]:
#Putting tensors (and models) on GPU
#Create a tensor (default CPU)
tensor = torch.tensor([1,2,3])
#Tensor not on GPU 
print(f"Tensor is: {tensor} \nand device is: {tensor.device}")

Tensor is: tensor([1, 2, 3]) 
and device is: cpu


In [7]:
tensor_gpu = tensor.to(device)
print(f"The device now is: {tensor_gpu.device}")

The device now is: cuda:0


In [8]:
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [9]:
#Moving tensor back to the CPU
#If tensor is on GPU, can't transform it to NumPy
tensor_gpu.numpy()

TypeError: ignored

In [10]:
#To fix this issue we can set to CPU again
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_gpu

tensor([1, 2, 3], device='cuda:0')