<a href="https://colab.research.google.com/github/himanshu3103/PyTorch/blob/main/Pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch
# Create random tensor
rand_tensor = torch.rand(7,7)
print(f"Random 7X7 tensor is: {rand_tensor}")

Random 7X7 tensor is: tensor([[0.7752, 0.7122, 0.1099, 0.8054, 0.8627, 0.4708, 0.3476],
        [0.5214, 0.6715, 0.7405, 0.7459, 0.4598, 0.1169, 0.0140],
        [0.1121, 0.8255, 0.6763, 0.0804, 0.6501, 0.6318, 0.5915],
        [0.1166, 0.2095, 0.5201, 0.6677, 0.0467, 0.1931, 0.6254],
        [0.4878, 0.0426, 0.5435, 0.0638, 0.0553, 0.3960, 0.7523],
        [0.2613, 0.5333, 0.9153, 0.8050, 0.0774, 0.1983, 0.8137],
        [0.5898, 0.7491, 0.1305, 0.4186, 0.5670, 0.5434, 0.8965]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
rand_tensor_2 = torch.rand(1,7)
print(f"Random tensor 2: {rand_tensor_2}")
print(f"Random tensor 2 shape: {rand_tensor_2.shape}")
# Perform matrix multiplication 
rand_tensor_2_transposed = rand_tensor_2.reshape(7,1) #transposing the rand tensor matrix multiplication
mat_mul_result = torch.matmul(rand_tensor,rand_tensor_2_transposed)
print(f"Matrix Multiplication gives: {mat_mul_result}")

Random tensor 2: tensor([[0.3094, 0.9987, 0.0793, 0.8677, 0.1470, 0.0574, 0.1002]])
Random tensor 2 shape: torch.Size([1, 7])
Matrix Multiplication gives: tensor([[1.8474],
        [1.6136],
        [1.1736],
        [0.9464],
        [0.3982],
        [1.4888],
        [1.5085]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
rand_tensor_1 = torch.rand(7,7)
rand_tensor_2 = torch.rand(1,7)
rand_tensor_2_transposed = rand_tensor_2.reshape(7,1)
# Matrix multiply tensors
mat_mul_result = torch.matmul(rand_tensor_1,rand_tensor_2_transposed)
print(f"Random Tensor 1: {rand_tensor_1} \nand its shape: {rand_tensor_1.shape}")
print(f"Random Tensor 2: {rand_tensor_2} \nand its shape: {rand_tensor_2.shape}")
print(f"Matrix multiplication result: {mat_mul_result}")

Random Tensor 1: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) 
and its shape: torch.Size([7, 7])
Random Tensor 2: tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]) 
and its shape: torch.Size([1, 7])
Matrix multiplication result: tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
RANDOM_SEED_GPU = 1234
torch.cuda.manual_seed(RANDOM_SEED_GPU)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"The current device is: {device}")

# Create two random tensors on GPU
rand_tensor_gpu_1 = torch.rand(2,3).to(device)
rand_tensor_gpu_2 = torch.rand(2,3).to(device)
print(f"Random tensor 1 on gpu is: {rand_tensor_gpu_1}")
print(f"Random tensor 2 on gpu is: {rand_tensor_gpu_2}")

The current device is: cuda
Random tensor 1 on gpu is: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
Random tensor 2 on gpu is: tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
print(f"Random tensor 1 on gpu is: {rand_tensor_gpu_1}")
print(f"Random tensor 2 on gpu is: {rand_tensor_gpu_2}")
mat_mul_result = torch.matmul(rand_tensor_gpu_1,rand_tensor_gpu_2.reshape(3,2))
print(f"Matrix Multiplication Result: {mat_mul_result}")

Random tensor 1 on gpu is: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
Random tensor 2 on gpu is: tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
Matrix Multiplication Result: tensor([[0.4759, 0.2931],
        [0.6074, 0.5855]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
max = torch.max(mat_mul_result)
print(f"Max value of the matrix mul: {max}")
# Find min
min = torch.min(mat_mul_result)
print(f"Min value of the matrix mul : {min}")

Max value of the matrix mul: 0.6073753833770752
Min value of the matrix mul : 0.2930890917778015


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
arg_max = torch.argmax(mat_mul_result)
print(f"Arg max: {arg_max}")
# Find arg min
arg_min = torch.argmin(mat_mul_result)
print(f"Arg min: {arg_min}")

Arg max: 2
Arg min: 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
rand_tensor = torch.rand(1,1,1,10)

# Remove single dimensions
rand_tensor_squeezed = rand_tensor.squeeze()

# Print out tensors and their shapes
print(f"Random Tensor: {rand_tensor} \nand shape: {rand_tensor.shape}")
print(f"Squeezed Tensor: {rand_tensor_squeezed} \nand shape: {rand_tensor_squeezed.shape}")

Random Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) 
and shape: torch.Size([1, 1, 1, 10])
Squeezed Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) 
and shape: torch.Size([10])
